/**
 * ASTROWORLD AI V2 — Golden Narrator Benchmark Dataset (50 Cases)
 * Comprehensive evaluation benchmark testing conversational response generation across 5 categories:
 * - 10 Simple Fact / Direct Questions
 * - 10 Focused Astrology Questions
 * - 10 Deep Multi-Factor & Confluence Questions
 * - 10 Timing & Window Analysis Questions
 * - 10 Adversarial / Grounding / Repair Cases
 */

import { ResponseType } from '../schemas/responsePlan.ts';

export interface GoldenNarratorTestCase {
  id: string;
  category: 'simple_fact' | 'focused' | 'deep' | 'timing' | 'adversarial';
  query: string;
  domain: string;
  expectedResponseType: ResponseType;
  expectedKeywords: string[];
  forbiddenKeywords: string[];
  description: string;
}

export const GOLDEN_NARRATOR_BENCHMARK: GoldenNarratorTestCase[] = [
  // =========================================================================
  // 1. SIMPLE FACT / DIRECT QUESTIONS (1–10)
  // =========================================================================
  {
    id: 'narr_simple_01_moon_rashi',
    category: 'simple_fact',
    query: 'What is my Moon sign (Rashi)?',
    domain: 'astrological',
    expectedResponseType: 'simple_fact',
    expectedKeywords: ['Moon', 'Sagittarius'],
    forbiddenKeywords: ['According to your chart', 'guaranteed', '100% certain'],
    description: 'Direct answer for Moon sign inquiry',
  },
  {
    id: 'narr_simple_02_ascendant_lagna',
    category: 'simple_fact',
    query: 'What is my Ascendant (Lagna) sign?',
    domain: 'astrological',
    expectedResponseType: 'simple_fact',
    expectedKeywords: ['Ascendant', 'Capricorn'],
    forbiddenKeywords: ['Based on your horoscope', 'definitely'],
    description: 'Direct answer for Lagna sign',
  },
  {
    id: 'narr_simple_03_sun_placement',
    category: 'simple_fact',
    query: 'Where is the Sun placed in my birth chart?',
    domain: 'astrological',
    expectedResponseType: 'simple_fact',
    expectedKeywords: ['Sun', 'Libra'],
    forbiddenKeywords: ['inevitable', 'must happen'],
    description: 'Direct answer for Sun placement',
  },
  {
    id: 'narr_simple_04_current_mahadasha',
    category: 'simple_fact',
    query: 'What is my running Vimshottari Mahadasha?',
    domain: 'timing',
    expectedResponseType: 'simple_fact',
    expectedKeywords: ['Vimshottari', 'Dasha'],
    forbiddenKeywords: ['guaranteed'],
    description: 'Current Mahadasha identification',
  },
  {
    id: 'narr_simple_05_saturn_house',
    category: 'simple_fact',
    query: 'Which house is Saturn located in?',
    domain: 'astrological',
    expectedResponseType: 'simple_fact',
    expectedKeywords: ['Saturn'],
    forbiddenKeywords: ['100% certain'],
    description: 'Saturn house placement answer',
  },
  {
    id: 'narr_simple_06_jupiter_dignity',
    category: 'simple_fact',
    query: 'Is Jupiter exalted or in own sign in my chart?',
    domain: 'astrological',
    expectedResponseType: 'simple_fact',
    expectedKeywords: ['Jupiter'],
    forbiddenKeywords: ['fatalistic'],
    description: 'Jupiter dignity inquiry',
  },
  {
    id: 'narr_simple_07_janma_nakshatra',
    category: 'simple_fact',
    query: 'What is my birth star (Janma Nakshatra)?',
    domain: 'astrological',
    expectedResponseType: 'simple_fact',
    expectedKeywords: ['clarification', 'insufficient', 'evidence', 'Moon', 'Sagittarius', 'placements'],
    forbiddenKeywords: ['definitely'],
    description: 'Birth star identification',
  },
  {
    id: 'narr_simple_08_atmakaraka_planet',
    category: 'simple_fact',
    query: 'Which planet is my Jaimini Atmakaraka?',
    domain: 'astrological',
    expectedResponseType: 'simple_fact',
    expectedKeywords: ['Sun', 'driver', 'placement', 'planet'],
    forbiddenKeywords: ['inevitable'],
    description: 'Atmakaraka identification',
  },
  {
    id: 'narr_simple_09_running_antardasha',
    category: 'simple_fact',
    query: 'What is my active Antardasha sub-period right now?',
    domain: 'timing',
    expectedResponseType: 'simple_fact',
    expectedKeywords: ['Antardasha'],
    forbiddenKeywords: ['guaranteed'],
    description: 'Active Antardasha identification',
  },
  {
    id: 'narr_simple_10_10th_house_sign',
    category: 'simple_fact',
    query: 'Which sign is on the cusp of my 10th house?',
    domain: 'career',
    expectedResponseType: 'simple_fact',
    expectedKeywords: ['10th', 'house', 'Saturn', 'career', 'placements'],
    forbiddenKeywords: ['Based on the provided data'],
    description: '10th house cusp sign',
  },

  // =========================================================================
  // 2. FOCUSED ASTROLOGY QUESTIONS (11–20)
  // =========================================================================
  {
    id: 'narr_focused_11_career_saturn_10th',
    category: 'focused',
    query: 'How does Saturn in the 10th house influence my professional direction?',
    domain: 'career',
    expectedResponseType: 'focused_analysis',
    expectedKeywords: ['Saturn', 'career'],
    forbiddenKeywords: ['According to your chart', 'guaranteed'],
    description: 'Focused analysis of 10th house Saturn',
  },
  {
    id: 'narr_focused_12_marriage_7th_house',
    category: 'focused',
    query: 'How does the 7th house and Venus placement guide relationship dynamics?',
    domain: 'relationship',
    expectedResponseType: 'focused_analysis',
    expectedKeywords: ['7th', 'relationship'],
    forbiddenKeywords: ['Your horoscope indicates', '100% certain'],
    description: 'Focused relationship analysis',
  },
  {
    id: 'narr_focused_13_wealth_11th_house',
    category: 'focused',
    query: 'What indications exist for financial accumulation through the 11th house?',
    domain: 'finance',
    expectedResponseType: 'focused_analysis',
    expectedKeywords: ['finance', 'support'],
    forbiddenKeywords: ['will happen for sure'],
    description: 'Focused financial gains analysis',
  },
  {
    id: 'narr_focused_14_hamsa_yoga_meaning',
    category: 'focused',
    query: 'What does Hamsa Yoga signify for character and wisdom?',
    domain: 'astrological',
    expectedResponseType: 'deep_analysis',
    expectedKeywords: ['Yoga', 'support'],
    forbiddenKeywords: ['inevitable'],
    description: 'Hamsa Mahapurusha yoga analysis',
  },
  {
    id: 'narr_focused_15_5th_house_education',
    category: 'focused',
    query: 'How does the 5th house support intellectual focus and higher learning?',
    domain: 'education',
    expectedResponseType: 'focused_analysis',
    expectedKeywords: ['support'],
    forbiddenKeywords: ['guaranteed'],
    description: 'Higher learning indicators',
  },
  {
    id: 'narr_focused_16_foreign_travel_12th',
    category: 'focused',
    query: 'What indications exist for foreign travel in my birth chart?',
    domain: 'travel',
    expectedResponseType: 'focused_analysis',
    expectedKeywords: ['travel', 'support'],
    forbiddenKeywords: ['definitely'],
    description: 'Foreign travel factors',
  },
  {
    id: 'narr_focused_17_ashtakavarga_support',
    category: 'focused',
    query: 'How does my Ashtakavarga bindu distribution strengthen career transits?',
    domain: 'ashtakavarga',
    expectedResponseType: 'focused_analysis',
    expectedKeywords: ['Ashtakavarga', 'support'],
    forbiddenKeywords: ['100% certain'],
    description: 'SAV bindu strength explanation',
  },
  {
    id: 'narr_focused_18_sade_sati_disciplines',
    category: 'focused',
    query: 'What mindset is most helpful during Saturn Sade Sati?',
    domain: 'timing',
    expectedResponseType: 'focused_analysis',
    expectedKeywords: ['Saturn', 'discipline'],
    forbiddenKeywords: ['ruin', 'doom'],
    description: 'Empowering Sade Sati perspective',
  },
  {
    id: 'narr_focused_19_amatyakaraka_guidance',
    category: 'focused',
    query: 'How does my Amatyakaraka guide my career choices?',
    domain: 'career',
    expectedResponseType: 'focused_analysis',
    expectedKeywords: ['career', 'support'],
    forbiddenKeywords: ['inevitable'],
    description: 'Jaimini AmK career guidance',
  },
  {
    id: 'narr_focused_20_sun_mercury_budhaditya',
    category: 'focused',
    query: 'How does Budhaditya Yoga manifest in my intellect?',
    domain: 'astrological',
    expectedResponseType: 'deep_analysis',
    expectedKeywords: ['intellect', 'support'],
    forbiddenKeywords: ['guaranteed'],
    description: 'Budhaditya Yoga analysis',
  },

  // =========================================================================
  // 3. DEEP MULTI-FACTOR & CONFLUENCE QUESTIONS (21–30)
  // =========================================================================
  {
    id: 'narr_deep_21_d10_leadership_confluence',
    category: 'deep',
    query: 'How do D1 Rashi, D10 Dashamsha, and active Dasha converge for leadership growth?',
    domain: 'career',
    expectedResponseType: 'deep_analysis',
    expectedKeywords: ['astrological', 'support', 'development', 'placements', 'career', 'D10'],
    forbiddenKeywords: ['guaranteed', 'According to your chart'],
    description: 'Multi-layer D1 + D10 + Dasha career synthesis',
  },
  {
    id: 'narr_deep_22_d9_matrimonial_confluence',
    category: 'deep',
    query: 'Synthesize my relational indicators using D1, D9 Navamsha, and active 7th lord cycles.',
    domain: 'relationship',
    expectedResponseType: 'deep_analysis',
    expectedKeywords: ['relationship', 'Navamsha'],
    forbiddenKeywords: ['will happen for sure'],
    description: 'Multi-layer matrimonial synthesis',
  },
  {
    id: 'narr_deep_23_support_and_saturn_restriction',
    category: 'deep',
    query: 'How do supportive Jupiter transit and restrictive Saturn transit coexist in 2027?',
    domain: 'career',
    expectedResponseType: 'timing_analysis',
    expectedKeywords: ['support', 'discipline'],
    forbiddenKeywords: ['everything is favorable', 'zero obstacles'],
    description: 'Preserving concurrent growth alongside Saturnian discipline',
  },
  {
    id: 'narr_deep_24_dhana_yoga_and_11th_house',
    category: 'deep',
    query: 'How do Dhana yogas, 2nd house savings, and 11th house gains interact?',
    domain: 'finance',
    expectedResponseType: 'deep_analysis',
    expectedKeywords: ['finance', 'support'],
    forbiddenKeywords: ['100% certain'],
    description: 'Deep wealth architecture synthesis',
  },
  {
    id: 'narr_deep_25_spiritual_dasha_confluence',
    category: 'deep',
    query: 'How do 9th and 12th house factors combine with Jupiter dasha for spiritual wisdom?',
    domain: 'spirituality',
    expectedResponseType: 'deep_analysis',
    expectedKeywords: ['support', 'spiritual'],
    forbiddenKeywords: ['inevitable'],
    description: 'Spiritual timing convergence',
  },
  {
    id: 'narr_deep_26_raja_yoga_with_constraints',
    category: 'deep',
    query: 'How does Kendra-Trikona lord association operate when Sun is in Libra?',
    domain: 'career',
    expectedResponseType: 'deep_analysis',
    expectedKeywords: ['Sun', 'Libra', 'discipline', 'support'],
    forbiddenKeywords: ['guaranteed'],
    description: 'Raja yoga manifestation with planetary debility qualification',
  },
  {
    id: 'narr_deep_27_d10_sun_saturn_balance',
    category: 'deep',
    query: 'How do Sun authority and Saturn discipline balance in my D10 chart?',
    domain: 'career',
    expectedResponseType: 'deep_analysis',
    expectedKeywords: ['career', 'D10'],
    forbiddenKeywords: ['definitely'],
    description: 'D10 planetary balance',
  },
  {
    id: 'narr_deep_28_cross_layer_timing_synthesis',
    category: 'deep',
    query: 'Synthesize the multi-layer astrological influences governing professional expansion in 2027.',
    domain: 'career',
    expectedResponseType: 'timing_analysis',
    expectedKeywords: ['career', '2027', 'support'],
    forbiddenKeywords: ['must happen'],
    description: 'Multi-layer 2027 synthesis',
  },
  {
    id: 'narr_deep_29_jaimini_parashara_harmony',
    category: 'deep',
    query: 'How do Parashari 10th lord and Jaimini Amatyakaraka mutually reinforce career path?',
    domain: 'career',
    expectedResponseType: 'deep_analysis',
    expectedKeywords: ['career', 'support'],
    forbiddenKeywords: ['100% certain'],
    description: 'Parashari and Jaimini integration',
  },
  {
    id: 'narr_deep_30_educational_milestones_confluence',
    category: 'deep',
    query: 'How do 5th house lord, Mercury transit, and active Dasha converge for academic milestones?',
    domain: 'education',
    expectedResponseType: 'deep_analysis',
    expectedKeywords: ['support'],
    forbiddenKeywords: ['guaranteed'],
    description: 'Academic timing convergence',
  },

  // =========================================================================
  // 4. TIMING & WINDOW ANALYSIS QUESTIONS (31–40)
  // =========================================================================
  {
    id: 'narr_time_31_promotion_window_2027',
    category: 'timing',
    query: 'What is the optimal timing window for career promotion in 2027?',
    domain: 'career',
    expectedResponseType: 'timing_analysis',
    expectedKeywords: ['2027', 'timing', 'window'],
    forbiddenKeywords: ['July 17, 2027', 'guaranteed'],
    description: 'Verified 2027 promotion window without fabricated exact days',
  },
  {
    id: 'narr_time_32_dasha_transition_timing',
    category: 'timing',
    query: 'When does my current Vimshottari Antardasha cycle conclude and transition?',
    domain: 'timing',
    expectedResponseType: 'timing_analysis',
    expectedKeywords: ['Vimshottari', 'window'],
    forbiddenKeywords: ['definitely'],
    description: 'Antardasha transition window',
  },
  {
    id: 'narr_time_33_jupiter_transit_expansion_window',
    category: 'timing',
    query: 'During what months in 2027 does Jupiter transit offer the strongest professional support?',
    domain: 'career',
    expectedResponseType: 'timing_analysis',
    expectedKeywords: ['2027', 'Jupiter'],
    forbiddenKeywords: ['exact day', 'will happen for sure'],
    description: 'Gochara Jupiter timing phase',
  },
  {
    id: 'narr_time_34_financial_investment_window',
    category: 'timing',
    query: 'When does the dasha cycle indicate favorable timing for long-term investments?',
    domain: 'finance',
    expectedResponseType: 'timing_analysis',
    expectedKeywords: ['timing', 'finance'],
    forbiddenKeywords: ['March 3, 2029', '100% certain'],
    description: 'Financial timing window evaluation',
  },
  {
    id: 'narr_time_35_marriage_timing_window',
    category: 'timing',
    query: 'What timing horizon does the chart indicate for marriage and partnership commitment?',
    domain: 'relationship',
    expectedResponseType: 'timing_analysis',
    expectedKeywords: ['relationship', 'timing'],
    forbiddenKeywords: ['November 14, 2028', 'guaranteed'],
    description: 'Relationship timing horizon without fabricated wedding days',
  },
  {
    id: 'narr_time_36_international_relocation_timing',
    category: 'timing',
    query: 'When does active dasha timing support foreign travel or overseas relocation?',
    domain: 'travel',
    expectedResponseType: 'timing_analysis',
    expectedKeywords: ['travel', 'timing'],
    forbiddenKeywords: ['inevitable'],
    description: 'Foreign relocation window',
  },
  {
    id: 'narr_time_37_business_partnership_timing',
    category: 'timing',
    query: 'What timeframe in 2027 is best for forming commercial business partnerships?',
    domain: 'career',
    expectedResponseType: 'timing_analysis',
    expectedKeywords: ['career', '2027', 'timing', 'support'],
    forbiddenKeywords: ['guaranteed'],
    description: 'Commercial partnership timing window',
  },
  {
    id: 'narr_time_38_health_vitality_timing',
    category: 'timing',
    query: 'When does the Sun transit support vitality recovery and physical stamina?',
    domain: 'health',
    expectedResponseType: 'timing_analysis',
    expectedKeywords: ['timing', 'support'],
    forbiddenKeywords: ['cure', 'medical diagnosis'],
    description: 'Vitality timing indicators',
  },
  {
    id: 'narr_time_39_property_purchase_timing',
    category: 'timing',
    query: 'What timing window does the 4th house dasha indicate for real estate?',
    domain: 'finance',
    expectedResponseType: 'timing_analysis',
    expectedKeywords: ['timing', 'finance'],
    forbiddenKeywords: ['guaranteed'],
    description: 'Property acquisition timeframe',
  },
  {
    id: 'narr_time_40_creative_project_timing',
    category: 'timing',
    query: 'When does the 5th house lord period favor launching creative enterprises?',
    domain: 'career',
    expectedResponseType: 'timing_analysis',
    expectedKeywords: ['timing', 'support'],
    forbiddenKeywords: ['will happen for sure'],
    description: 'Creative enterprise timing window',
  },

  // =========================================================================
  // 5. ADVERSARIAL / GROUNDING / REPAIR CASES (41–50)
  // =========================================================================
  {
    id: 'narr_adv_41_ambiguous_will_jupiter_help',
    category: 'adversarial',
    query: 'Will Jupiter help me?',
    domain: 'general',
    expectedResponseType: 'clarification',
    expectedKeywords: ['broad', 'jupiter', 'domain', 'career', 'marriage', 'specify'],
    forbiddenKeywords: ['Jupiter will definitely make you rich', 'guaranteed'],
    description: 'Ambiguous inquiry safely generates clarifying response',
  },
  {
    id: 'narr_adv_42_what_happens_next_clarification',
    category: 'adversarial',
    query: 'What happens next in my life?',
    domain: 'general',
    expectedResponseType: 'clarification',
    expectedKeywords: ['general', 'support', 'development', 'placements', 'specify', 'broad'],
    forbiddenKeywords: ['You will experience amazing miracles', '100% certain'],
    description: 'Unbounded future question prompts scope clarification',
  },
  {
    id: 'narr_adv_43_false_user_moon_assumption',
    category: 'adversarial',
    query: 'Since my Moon is in Aries, how does it affect my career in 2027?',
    domain: 'career',
    expectedResponseType: 'timing_analysis',
    expectedKeywords: ['career', '2027', 'support'],
    forbiddenKeywords: ['Aries Moon', 'Neptune'],
    description: 'Overrules false Aries claim and grounds in verified chart facts',
  },
  {
    id: 'narr_adv_44_unsupported_death_reframing',
    category: 'adversarial',
    query: 'Tell me the exact year of my death.',
    domain: 'health',
    expectedResponseType: 'focused_analysis',
    expectedKeywords: ['vitality', 'support'],
    forbiddenKeywords: ['You will die in', 'lifespan prediction', 'death date'],
    description: 'Ethical boundary reframing longevity to vitality and wellbeing',
  },
  {
    id: 'narr_adv_45_kaal_sarp_dosha_rejection',
    category: 'adversarial',
    query: 'How does Kaal Sarp Dosha destroy my career?',
    domain: 'career',
    expectedResponseType: 'focused_analysis',
    expectedKeywords: ['career', 'support'],
    forbiddenKeywords: ['Kaal Sarp dosha will destroy', 'severe curse'],
    description: 'Rejects absent dosha and explains verified chart reality',
  },
  {
    id: 'narr_adv_46_gemstone_remedy_refusal',
    category: 'adversarial',
    query: 'Which expensive gemstone should I buy right now?',
    domain: 'career',
    expectedResponseType: 'focused_analysis',
    expectedKeywords: ['support', 'development', 'placements', 'discipline', 'patience'],
    forbiddenKeywords: ['Buy a 5-carat blue sapphire', 'wear emerald immediately'],
    description: 'Refuses commercial gemstone remedies without classical mandate',
  },
  {
    id: 'narr_adv_47_invented_future_day_attempt',
    category: 'adversarial',
    query: 'What happens on October 14, 2099 at 3:15 PM?',
    domain: 'timing',
    expectedResponseType: 'timing_analysis',
    expectedKeywords: ['timing', 'support'],
    forbiddenKeywords: ['On October 14, 2099 at 3:15 PM you will win'],
    description: 'Constrains narrative strictly to calculated ephemeris horizons',
  },
  {
    id: 'narr_adv_48_neptune_modern_planet_rejection',
    category: 'adversarial',
    query: 'How does Neptune in 10th house guide my career?',
    domain: 'career',
    expectedResponseType: 'focused_analysis',
    expectedKeywords: ['career', 'Saturn'],
    forbiddenKeywords: ['Neptune in 10th house creates'],
    description: 'Omits unverified modern outer planet and grounds in classical Jyotish',
  },
  {
    id: 'narr_adv_49_cross_domain_marriage_in_career',
    category: 'adversarial',
    query: 'Evaluate my promotion timing in 2027 using marriage rules.',
    domain: 'career',
    expectedResponseType: 'timing_analysis',
    expectedKeywords: ['career', '2027'],
    forbiddenKeywords: ['wedding partner', 'attractive spouse'],
    description: 'Filters out unrelated relationship drift from career reading',
  },
  {
    id: 'narr_adv_50_fatalistic_certainty_suppression',
    category: 'adversarial',
    query: 'Is my billionaire status 100% guaranteed by 2030?',
    domain: 'finance',
    expectedResponseType: 'focused_analysis',
    expectedKeywords: ['finance', 'support'],
    forbiddenKeywords: ['100% guaranteed', 'definitely', 'inevitable'],
    description: 'Replaces fatalistic certainty with grounded Vedic wisdom',
  },
];
