/**
 * ASTROWORLD AI V2 — Post Response Grounding Validator
 * Verifies that the draft prose generated by the narrator does not introduce
 * unapproved entities, fabricated dates, forbidden certainty, or domain drift.
 */

import { QuestionPlan } from '../schemas/questionPlan.ts';
import { ReasoningPacket } from '../schemas/reasoningPacket.ts';
import { ApprovedClaimSet } from '../schemas/claimPacket.ts';
import { ExtractedResponseClaim, PostResponseValidationResult } from '../schemas/responsePlan.ts';

const FORBIDDEN_ENTITIES = ['neptune', 'uranus', 'pluto', 'chiron', 'planet x'];

const REMEDY_REGEX =
  /\b(wear\s+a\s+gemstone|wear\s+ruby|wear\s+sapphire|wear\s+emerald|chant\s+mantra|perform\s+puja|fast\s+on\s+tuesday|fast\s+on\s+saturday|remedy|buy\s+a\s+.*(?:sapphire|ruby|emerald|gemstone)|sapphire|emerald|ruby|gemstone)\b/i;

export class PostResponseGroundingValidator {
  /**
   * Validates extracted response claims against the ApprovedClaimSet.
   */
  public validate(
    extractedClaims: ExtractedResponseClaim[],
    fullDraftText: string,
    approvedClaimSet: ApprovedClaimSet,
    reasoning: ReasoningPacket,
    plan: QuestionPlan
  ): PostResponseValidationResult {
    const violations: string[] = [];
    const unapprovedEntities: string[] = [];
    const unapprovedDates: string[] = [];
    const unapprovedRemedies: string[] = [];
    const certaintyEscalations: string[] = [];
    let suppressedContradictions = false;

    // Collect all approved tokens and entities
    const approvedCombinedText = approvedClaimSet.claims.map(c => c.text.toLowerCase()).join(' ');

    const approvedPlanets = new Set<string>();
    for (const c of approvedClaimSet.claims) {
      if (c.astrologicalEntities) {
        c.astrologicalEntities.forEach(e => approvedPlanets.add(e.toLowerCase()));
      }
    }

    const approvedDates = new Set<string>();
    for (const c of approvedClaimSet.claims) {
      if (c.temporalScope?.startIso) approvedDates.add(c.temporalScope.startIso);
      if (c.temporalScope?.endIso) approvedDates.add(c.temporalScope.endIso);
    }

    // 1. Check Extracted Claims
    for (const claim of extractedClaims) {
      // Check Unapproved Planets / Modern Inventions
      for (const p of claim.planets) {
        const lowerP = p.toLowerCase();
        if (FORBIDDEN_ENTITIES.includes(lowerP)) {
          unapprovedEntities.push(p);
          violations.push(`Unapproved modern astrological entity "${p}" found in generated response.`);
        }
      }

      // Check Unapproved Yogas (e.g. Kaal Sarp when not in approved claims)
      for (const y of claim.yogas) {
        const lowerY = y.toLowerCase();
        if (lowerY === 'atmakaraka' || lowerY === 'amatyakaraka') continue;
        const isNegated =
          claim.claimText.toLowerCase().includes('not formed') ||
          claim.claimText.toLowerCase().includes('not present') ||
          claim.claimText.toLowerCase().includes('does not form') ||
          claim.claimText.toLowerCase().includes('is not present');
        if (!isNegated && !approvedCombinedText.includes(lowerY)) {
          unapprovedEntities.push(y);
          violations.push(`Unapproved yoga/dosha "${y}" found in generated response.`);
        }
      }

      // Check Certainty Escalation
      if (claim.certaintyLevel === 'certain') {
        certaintyEscalations.push(claim.claimText);
        violations.push(`Forbidden fatalistic certainty detected in statement: "${claim.claimText}"`);
      }

      // Check Fabricated Dates (Specific Days)
      for (const d of claim.referencedDates) {
        if (d.includes(',') || d.match(/\b(january|february|march|april|may|june|july|august|september|october|november|december)\b/i)) {
          const isApprovedDate = Array.from(approvedDates).some(ad => ad.includes(d) || d.includes(ad)) ||
            approvedCombinedText.includes(d.toLowerCase());
          if (!isApprovedDate) {
            unapprovedDates.push(d);
            violations.push(`Fabricated specific event date "${d}" not found in ApprovedClaimSet.`);
          }
        }
      }
    }

    // 2. Check Unapproved Remedies
    if (REMEDY_REGEX.test(fullDraftText)) {
      const isNegated =
        /\b(no\s+(?:gemstone|remedy|commercial\s+remedy|ritual)|not\s+prescribe|not\s+recommend|refuse|without\s+remedy|does\s+not\s+guarantee|no\s+.*guarantee)\b/i.test(fullDraftText);
      if (!isNegated) {
        const hasApprovedRemedy = approvedClaimSet.claims.some(c => c.ruleIds.length > 0 && REMEDY_REGEX.test(c.text));
        if (!hasApprovedRemedy) {
          unapprovedRemedies.push('Commercial remedy or unverified ritual detected');
          violations.push('Unapproved astrological remedy detected without approved classical rule lineage.');
        }
      }
    }

    // 3. Check Contradiction Suppression (Mixed State)
    if (reasoning.direction === 'mixed') {
      const lowerDraft = fullDraftText.toLowerCase();
      const mentionsDisciplineOrConstraint =
        lowerDraft.includes('discipline') ||
        lowerDraft.includes('constraint') ||
        lowerDraft.includes('structural') ||
        lowerDraft.includes('pressure') ||
        lowerDraft.includes('patience') ||
        lowerDraft.includes('steady');

      if (!mentionsDisciplineOrConstraint) {
        suppressedContradictions = true;
        violations.push('Contradiction suppression: Mixed chart indications were flattened into unconstrained optimism.');
      }
    }

    const valid = violations.length === 0;

    return {
      valid,
      violations,
      unapprovedEntities,
      unapprovedDates,
      unapprovedRemedies,
      certaintyEscalations,
      suppressedContradictions,
    };
  }
}
