/**
 * ASTROWORLD AI V2 — Golden Claim Validation Benchmark Dataset (50 Cases)
 * Rigorous evaluation suite testing the Grounding Firewall across 5 core categories:
 * - 10 Factual Grounding & Entity Verification Cases
 * - 10 Temporal Accuracy & Date Precision Cases
 * - 10 Lineage & Source Provenance Cases
 * - 10 Certainty Control & Contradiction Preservation Cases
 * - 10 Adversarial / Invention / Drift / Safety Firewall Cases
 */

import { ClaimItem, ClaimType, ClaimStrength } from '../schemas/claimPacket.ts';

export interface GoldenClaimTestCase {
  id: string;
  category: 'factual' | 'temporal' | 'lineage' | 'certainty_contradiction' | 'adversarial';
  description: string;
  query: string;
  candidateClaim: ClaimItem;
  expectedAllowed: boolean;
  expectedFailedCheckKeyword?: string;
}

export const GOLDEN_CLAIM_BENCHMARK: GoldenClaimTestCase[] = [
  // =========================================================================
  // 1. FACTUAL GROUNDING & ENTITY VERIFICATION (1–10)
  // =========================================================================
  {
    id: 'claim_fact_01_valid_saturn_placement',
    category: 'factual',
    description: 'Valid placement of Saturn in Capricorn matching D1 facts',
    query: 'How does Saturn in the 10th house affect my career?',
    candidateClaim: {
      claimId: 'c_valid_saturn',
      text: 'The verified chart placement of Saturn (position: Capricorn 15.2°) acts as a primary astrological driver.',
      type: 'factual',
      strength: 'strong',
      evidenceIds: ['fact_saturn_1'],
      ruleIds: [],
      sourceIds: [],
      relevance: 'high',
      allowed: true,
      astrologicalEntities: ['Saturn', 'Capricorn'],
    },
    expectedAllowed: true,
  },
  {
    id: 'claim_fact_02_fabricated_neptune',
    category: 'factual',
    description: 'Rejection of modern planet Neptune absent from classical Vedic ephemeris',
    query: 'How does Neptune affect my spiritual life?',
    candidateClaim: {
      claimId: 'c_fake_neptune',
      text: 'Neptune in the 12th house provides deep intuitive illusions.',
      type: 'factual',
      strength: 'moderate',
      evidenceIds: ['fact_neptune_1'],
      ruleIds: [],
      sourceIds: [],
      relevance: 'high',
      allowed: true,
      astrologicalEntities: ['Neptune'],
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'Unverified astrological entity',
  },
  {
    id: 'claim_fact_03_valid_jupiter_transit',
    category: 'factual',
    description: 'Verified Gochara transit of Jupiter through the 5th house',
    query: 'What is Jupiter transit in 2027?',
    candidateClaim: {
      claimId: 'c_valid_jup_transit',
      text: 'The verified chart placement of Jupiter transit (position: Taurus 12°) provides supporting astrological background.',
      type: 'factual',
      strength: 'moderate',
      evidenceIds: ['fact_jupiter_transit_1'],
      ruleIds: [],
      sourceIds: [],
      relevance: 'high',
      allowed: true,
      astrologicalEntities: ['Jupiter'],
    },
    expectedAllowed: true,
  },
  {
    id: 'claim_fact_04_fabricated_pluto',
    category: 'factual',
    description: 'Rejection of fabricated Pluto placement',
    query: 'Does Pluto aspect my 10th house?',
    candidateClaim: {
      claimId: 'c_fake_pluto',
      text: 'Pluto in Scorpio creates extreme transformational intensity.',
      type: 'factual',
      strength: 'moderate',
      evidenceIds: ['fact_pluto_1'],
      ruleIds: [],
      sourceIds: [],
      relevance: 'high',
      allowed: true,
      astrologicalEntities: ['Pluto'],
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'Unverified astrological entity',
  },
  {
    id: 'claim_fact_05_valid_d10_sun',
    category: 'factual',
    description: 'Verified Sun placement in D10 Dashamsha',
    query: 'How is Sun placed in my D10 chart?',
    candidateClaim: {
      claimId: 'c_valid_d10_sun',
      text: 'The verified chart placement of Sun in D10 (varga_sign: Leo) acts as a primary astrological driver.',
      type: 'factual',
      strength: 'strong',
      evidenceIds: ['fact_d10_sun_1'],
      ruleIds: [],
      sourceIds: [],
      relevance: 'high',
      allowed: true,
      astrologicalEntities: ['Sun', 'Leo'],
    },
    expectedAllowed: true,
  },
  {
    id: 'claim_fact_06_fabricated_uranus',
    category: 'factual',
    description: 'Rejection of fabricated Uranus',
    query: 'What does Uranus signify?',
    candidateClaim: {
      claimId: 'c_fake_uranus',
      text: 'Uranus conjunct Mars creates unexpected disruptions.',
      type: 'factual',
      strength: 'moderate',
      evidenceIds: ['fact_uranus_1'],
      ruleIds: [],
      sourceIds: [],
      relevance: 'high',
      allowed: true,
      astrologicalEntities: ['Uranus'],
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'Unverified astrological entity',
  },
  {
    id: 'claim_fact_07_valid_d9_venus',
    category: 'factual',
    description: 'Verified Venus in D9 Navamsha',
    query: 'What is Venus in D9?',
    candidateClaim: {
      claimId: 'c_valid_d9_venus',
      text: 'The verified chart placement of Venus in D9 (varga_sign: Pisces) acts as a primary astrological driver.',
      type: 'factual',
      strength: 'strong',
      evidenceIds: ['fact_d9_venus_1'],
      ruleIds: [],
      sourceIds: [],
      relevance: 'high',
      allowed: true,
      astrologicalEntities: ['Venus', 'Pisces'],
    },
    expectedAllowed: true,
  },
  {
    id: 'claim_fact_08_fabricated_chiron',
    category: 'factual',
    description: 'Rejection of asteroid Chiron in Jyotish context',
    query: 'Where is Chiron placed?',
    candidateClaim: {
      claimId: 'c_fake_chiron',
      text: 'Chiron in the 6th house indicates wounded healing.',
      type: 'factual',
      strength: 'moderate',
      evidenceIds: ['fact_chiron_1'],
      ruleIds: [],
      sourceIds: [],
      relevance: 'high',
      allowed: true,
      astrologicalEntities: ['Chiron'],
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'Unverified astrological entity',
  },
  {
    id: 'claim_fact_09_valid_moon_nakshatra',
    category: 'factual',
    description: 'Verified Moon in Mula Nakshatra',
    query: 'What is my Janma Nakshatra?',
    candidateClaim: {
      claimId: 'c_valid_moon_nak',
      text: 'The verified chart placement of Moon (position: Sagittarius 0.5°) acts as a primary astrological driver.',
      type: 'factual',
      strength: 'strong',
      evidenceIds: ['fact_moon_1'],
      ruleIds: [],
      sourceIds: [],
      relevance: 'high',
      allowed: true,
      astrologicalEntities: ['Moon', 'Sagittarius'],
    },
    expectedAllowed: true,
  },
  {
    id: 'claim_fact_10_fabricated_planet_x',
    category: 'factual',
    description: 'Rejection of hypothetical Planet X',
    query: 'Is Planet X influencing my chart?',
    candidateClaim: {
      claimId: 'c_fake_planet_x',
      text: 'Planet X in the 1st house creates gravitational anomalies.',
      type: 'factual',
      strength: 'weak',
      evidenceIds: ['fact_x_1'],
      ruleIds: [],
      sourceIds: [],
      relevance: 'high',
      allowed: true,
      astrologicalEntities: ['Planet X'],
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'Unverified astrological entity',
  },

  // =========================================================================
  // 2. TEMPORAL ACCURACY & DATE PRECISION (11–20)
  // =========================================================================
  {
    id: 'claim_time_11_valid_dasha_range',
    category: 'temporal',
    description: 'Verified Vimshottari Dasha window matching computed dates',
    query: 'When is my active dasha period?',
    candidateClaim: {
      claimId: 'c_time_valid_dasha',
      text: 'The verified timing window (Jupiter Mahadasha) spans from 2026-07-22T00:00:00.000Z to 2028-03-22T00:00:00.000Z.',
      type: 'timing',
      strength: 'moderate',
      evidenceIds: ['fact_dasha_1'],
      ruleIds: [],
      sourceIds: [],
      temporalScope: {
        startIso: '2026-07-22T00:00:00.000Z',
        endIso: '2028-03-22T00:00:00.000Z',
      },
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: true,
  },
  {
    id: 'claim_time_12_fabricated_event_day',
    category: 'temporal',
    description: 'Rejection of fabricated specific day prediction not computed by ephemeris',
    query: 'When will I get promoted in 2027?',
    candidateClaim: {
      claimId: 'c_time_fake_day',
      text: 'You will receive your promotion on July 17, 2027 at exactly 2:00 PM.',
      type: 'timing',
      strength: 'strong',
      evidenceIds: ['fact_dasha_1'],
      ruleIds: [],
      sourceIds: [],
      temporalScope: {
        startIso: '2027-07-17T14:00:00.000Z',
        endIso: '2027-07-17T14:00:00.000Z',
      },
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'Fabricated specific event date',
  },
  {
    id: 'claim_time_13_valid_target_window_2027',
    category: 'temporal',
    description: 'Verified 2027 target inquiry window',
    query: 'Analyze promotion timing in 2027.',
    candidateClaim: {
      claimId: 'c_time_valid_2027',
      text: 'The verified timing window (Target Query Window 2027) spans from 2027-01-01T00:00:00.000Z to 2027-12-31T23:59:59.999Z.',
      type: 'timing',
      strength: 'strong',
      evidenceIds: ['fact_transit_1'],
      ruleIds: [],
      sourceIds: [],
      temporalScope: {
        startIso: '2027-01-01T00:00:00.000Z',
        endIso: '2027-12-31T23:59:59.999Z',
      },
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: true,
  },
  {
    id: 'claim_time_14_fabricated_wedding_day',
    category: 'temporal',
    description: 'Rejection of hallucinated exact wedding date',
    query: 'When will I get married?',
    candidateClaim: {
      claimId: 'c_time_fake_wedding',
      text: 'Your marriage is scheduled for November 14, 2028 without any doubt.',
      type: 'timing',
      strength: 'strong',
      evidenceIds: ['fact_dasha_1'],
      ruleIds: [],
      sourceIds: [],
      temporalScope: {
        startIso: '2028-11-14T00:00:00.000Z',
        endIso: '2028-11-14T00:00:00.000Z',
      },
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'Fabricated specific event date',
  },
  {
    id: 'claim_time_15_valid_transit_phase',
    category: 'temporal',
    description: 'Verified Gochara transit window',
    query: 'How long does Jupiter stay in transit?',
    candidateClaim: {
      claimId: 'c_time_valid_transit',
      text: 'The verified timing window spans from 2026-06-01T00:00:00.000Z to 2027-06-01T00:00:00.000Z.',
      type: 'timing',
      strength: 'moderate',
      evidenceIds: ['fact_transit_1'],
      ruleIds: [],
      sourceIds: [],
      temporalScope: {
        startIso: '2026-06-01T00:00:00.000Z',
        endIso: '2027-06-01T00:00:00.000Z',
      },
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: true,
  },
  {
    id: 'claim_time_16_malformed_start_date',
    category: 'temporal',
    description: 'Rejection of invalid date string format',
    query: 'When is the transit?',
    candidateClaim: {
      claimId: 'c_time_malformed',
      text: 'The timing window is active.',
      type: 'timing',
      strength: 'moderate',
      evidenceIds: ['fact_dasha_1'],
      ruleIds: [],
      sourceIds: [],
      temporalScope: {
        startIso: 'invalid-date-string-1234',
        endIso: '2027-12-31T00:00:00.000Z',
      },
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'malformed start date',
  },
  {
    id: 'claim_time_17_valid_antardasha_window',
    category: 'temporal',
    description: 'Verified Antardasha sub-period window',
    query: 'What is my current Antardasha window?',
    candidateClaim: {
      claimId: 'c_time_valid_ad',
      text: 'The active Vimshottari Antardasha spans from 2026-07-22T00:00:00.000Z to 2028-03-22T00:00:00.000Z.',
      type: 'timing',
      strength: 'moderate',
      evidenceIds: ['fact_dasha_1'],
      ruleIds: [],
      sourceIds: [],
      temporalScope: {
        startIso: '2026-07-22T00:00:00.000Z',
        endIso: '2028-03-22T00:00:00.000Z',
      },
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: true,
  },
  {
    id: 'claim_time_18_fabricated_lottery_date',
    category: 'temporal',
    description: 'Rejection of speculative jackpot date',
    query: 'When will I win money?',
    candidateClaim: {
      claimId: 'c_time_lottery',
      text: 'You will receive sudden gains on March 03, 2029.',
      type: 'timing',
      strength: 'strong',
      evidenceIds: ['fact_dasha_1'],
      ruleIds: [],
      sourceIds: [],
      temporalScope: {
        startIso: '2029-03-03T00:00:00.000Z',
        endIso: '2029-03-03T00:00:00.000Z',
      },
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'Fabricated specific event date',
  },
  {
    id: 'claim_time_19_valid_confluence_horizon',
    category: 'temporal',
    description: 'Verified confluence horizon matching Dasha & Gochara',
    query: 'When is peak career timing in 2027?',
    candidateClaim: {
      claimId: 'c_time_peak_2027',
      text: 'The peak confluence window spans across the 2027 calendar year.',
      type: 'timing',
      strength: 'strong',
      evidenceIds: ['fact_dasha_1', 'fact_transit_1'],
      ruleIds: [],
      sourceIds: [],
      temporalScope: {
        startIso: '2027-01-01T00:00:00.000Z',
        endIso: '2027-12-31T23:59:59.999Z',
      },
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: true,
  },
  {
    id: 'claim_time_20_malformed_end_date',
    category: 'temporal',
    description: 'Rejection of corrupted end date timestamp',
    query: 'When does the period end?',
    candidateClaim: {
      claimId: 'c_time_bad_end',
      text: 'The period ends on unknown date.',
      type: 'timing',
      strength: 'weak',
      evidenceIds: ['fact_dasha_1'],
      ruleIds: [],
      sourceIds: [],
      temporalScope: {
        startIso: '2026-01-01T00:00:00.000Z',
        endIso: 'not-a-valid-date',
      },
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'malformed end date',
  },

  // =========================================================================
  // 3. LINEAGE & SOURCE PROVENANCE (21–30)
  // =========================================================================
  {
    id: 'claim_lin_21_valid_bphs_citation',
    category: 'lineage',
    description: 'Valid BPHS classical citation with verified evidence lineage',
    query: 'What does BPHS say about the 10th house?',
    candidateClaim: {
      claimId: 'c_lin_bphs',
      text: 'According to BPHS Ch. 24 Sloka 110, 10th house strength brings career elevation.',
      type: 'interpretive',
      strength: 'moderate',
      evidenceIds: ['fact_saturn_1'],
      ruleIds: ['bphs_career_10th_general'],
      sourceIds: ['bphs_ch24_110'],
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: true,
  },
  {
    id: 'claim_lin_22_missing_all_lineage',
    category: 'lineage',
    description: 'Rejection of interpretive claim lacking both evidence and rule lineage',
    query: 'How does my career look?',
    candidateClaim: {
      claimId: 'c_lin_empty',
      text: 'You will rise to high authority because you have executive energy.',
      type: 'interpretive',
      strength: 'strong',
      evidenceIds: [],
      ruleIds: [],
      sourceIds: [],
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'missing required evidence or rule lineage',
  },
  {
    id: 'claim_lin_23_valid_phaladeepika_transit',
    category: 'lineage',
    description: 'Valid Phaladeepika Gochara lineage',
    query: 'How does Jupiter transit operate according to classical texts?',
    candidateClaim: {
      claimId: 'c_lin_phala',
      text: 'According to Phaladeepika Ch. 26 Sloka 15, Jupiter transit through the 5th house confers intellectual expansion.',
      type: 'interpretive',
      strength: 'moderate',
      evidenceIds: ['fact_jupiter_transit_1'],
      ruleIds: ['phaladeepika_gochara_jup_5th'],
      sourceIds: ['phala_ch26_15'],
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: true,
  },
  {
    id: 'claim_lin_24_invalid_evidence_id',
    category: 'lineage',
    description: 'Rejection of claim referencing fabricated evidence ID',
    query: 'Explain my Raja Yoga.',
    candidateClaim: {
      claimId: 'c_lin_fake_ev',
      text: 'Classical Raja Yoga brings power and prestige.',
      type: 'interpretive',
      strength: 'moderate',
      evidenceIds: ['fabricated_evidence_id_9999'],
      ruleIds: ['bphs_raja_yoga_1'],
      sourceIds: ['bphs_ch34'],
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'unverified evidence IDs',
  },
  {
    id: 'claim_lin_25_valid_saravali_varga',
    category: 'lineage',
    description: 'Valid Saravali D10 Dashamsha lineage',
    query: 'How does Saravali analyze Dashamsha?',
    candidateClaim: {
      claimId: 'c_lin_saravali',
      text: 'According to Saravali Ch. 3, D10 planets govern executive status.',
      type: 'interpretive',
      strength: 'moderate',
      evidenceIds: ['fact_d10_sun_1'],
      ruleIds: ['saravali_d10_principles'],
      sourceIds: ['saravali_ch3'],
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: true,
  },
  {
    id: 'claim_lin_26_prediction_missing_evidence',
    category: 'lineage',
    description: 'Rejection of qualified prediction without supporting evidence IDs',
    query: 'Will I succeed?',
    candidateClaim: {
      claimId: 'c_lin_pred_no_ev',
      text: 'The astrological factors support career expansion.',
      type: 'qualified_prediction',
      strength: 'moderate',
      evidenceIds: [],
      ruleIds: [],
      sourceIds: [],
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'missing required evidence or rule lineage',
  },
  {
    id: 'claim_lin_27_valid_jaimini_sutra',
    category: 'lineage',
    description: 'Valid Jaimini Upadesha Sutras lineage for Atmakaraka',
    query: 'What does Jaimini say about Atmakaraka?',
    candidateClaim: {
      claimId: 'c_lin_jaimini',
      text: 'According to Jaimini Sutras 1.1.11, Atmakaraka signifies the spiritual soul driver.',
      type: 'interpretive',
      strength: 'moderate',
      evidenceIds: ['fact_ak_1'],
      ruleIds: ['jaimini_atmakaraka_foundations'],
      sourceIds: ['jaimini_1_1_11'],
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: true,
  },
  {
    id: 'claim_lin_28_ghost_evidence_pointer',
    category: 'lineage',
    description: 'Rejection of ghost evidence ID in predictive claim',
    query: 'Evaluate 2027 timing.',
    candidateClaim: {
      claimId: 'c_lin_ghost',
      text: 'The astrological factors strongly support professional growth.',
      type: 'qualified_prediction',
      strength: 'strong',
      evidenceIds: ['ghost_id_xyz'],
      ruleIds: ['bphs_rule_1'],
      sourceIds: ['bphs_source_1'],
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'unverified evidence IDs',
  },
  {
    id: 'claim_lin_29_valid_source_summary',
    category: 'lineage',
    description: 'Valid source explanation citing verified classical authorities',
    query: 'What authorities were consulted?',
    candidateClaim: {
      claimId: 'c_lin_valid_source',
      text: 'Interpretive principles derived from classical Jyotish authorities: Brihat Parashara Hora Shastra; Phaladeepika.',
      type: 'source_explanation',
      strength: 'moderate',
      evidenceIds: [],
      ruleIds: ['bphs_rule_1', 'phala_rule_1'],
      sourceIds: ['bphs_ch24', 'phala_ch26'],
      relevance: 'medium',
      allowed: true,
    },
    expectedAllowed: true,
  },
  {
    id: 'claim_lin_30_fabricated_source_text',
    category: 'lineage',
    description: 'Rejection of claim citing unverified non-existent evidence',
    query: 'What is the basis?',
    candidateClaim: {
      claimId: 'c_lin_bad_source',
      text: 'According to secret manuscripts, unexpected miracles will occur.',
      type: 'interpretive',
      strength: 'strong',
      evidenceIds: ['fake_ev_123'],
      ruleIds: [],
      sourceIds: [],
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'unverified evidence IDs',
  },

  // =========================================================================
  // 4. CERTAINTY CONTROL & CONTRADICTION PRESERVATION (31–40)
  // =========================================================================
  {
    id: 'claim_cert_31_guaranteed_promotion_rejection',
    category: 'certainty_contradiction',
    description: 'Rejection of fatalistic "guaranteed" outcome wording',
    query: 'Will I get promoted in 2027?',
    candidateClaim: {
      claimId: 'c_cert_guaranteed',
      text: 'A promotion is guaranteed to happen in April 2027.',
      type: 'qualified_prediction',
      strength: 'strong',
      evidenceIds: ['fact_saturn_1'],
      ruleIds: ['bphs_rule_1'],
      sourceIds: ['bphs_source_1'],
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'Unsupported fatalistic certainty language',
  },
  {
    id: 'claim_cert_32_valid_probabilistic_support',
    category: 'certainty_contradiction',
    description: 'Approved controlled probabilistic phrasing "strongly supports"',
    query: 'How does the chart support promotion in 2027?',
    candidateClaim: {
      claimId: 'c_cert_valid_support',
      text: 'The converging chart layers and classical rules strongly support positive development in career.',
      type: 'qualified_prediction',
      strength: 'strong',
      evidenceIds: ['fact_saturn_1'],
      ruleIds: ['bphs_rule_1'],
      sourceIds: ['bphs_source_1'],
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: true,
  },
  {
    id: 'claim_cert_33_definitely_rejection',
    category: 'certainty_contradiction',
    description: 'Rejection of "definitely" certainty claim',
    query: 'Will I pass the examination?',
    candidateClaim: {
      claimId: 'c_cert_definitely',
      text: 'You will definitely pass the examination with top rank.',
      type: 'qualified_prediction',
      strength: 'strong',
      evidenceIds: ['fact_saturn_1'],
      ruleIds: ['bphs_rule_1'],
      sourceIds: ['bphs_source_1'],
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'Unsupported fatalistic certainty language',
  },
  {
    id: 'claim_cert_34_valid_mixed_preservation',
    category: 'certainty_contradiction',
    description: 'Approved synthesis preserving both supportive and restrictive factors',
    query: 'How do supportive Jupiter and restrictive Saturn interact in 2027?',
    candidateClaim: {
      claimId: 'c_cert_valid_mixed',
      text: 'The astrological indications support growth in career, but operate alongside structural factors requiring patience and discipline.',
      type: 'qualified_prediction',
      strength: 'mixed',
      evidenceIds: ['fact_saturn_1'],
      ruleIds: ['bphs_rule_1'],
      sourceIds: ['bphs_source_1'],
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: true,
  },
  {
    id: 'claim_cert_35_100_percent_certain_rejection',
    category: 'certainty_contradiction',
    description: 'Rejection of "100% certain" fatalistic claim',
    query: 'Are you sure about my marriage timing?',
    candidateClaim: {
      claimId: 'c_cert_100_percent',
      text: 'It is 100% certain that your partner will arrive in 2027.',
      type: 'qualified_prediction',
      strength: 'strong',
      evidenceIds: ['fact_saturn_1'],
      ruleIds: ['bphs_rule_1'],
      sourceIds: ['bphs_source_1'],
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'Unsupported fatalistic certainty language',
  },
  {
    id: 'claim_cert_36_contradiction_suppression_rejection',
    category: 'certainty_contradiction',
    description: 'Rejection of "Everything is favorable" when chart state is mixed',
    query: 'Is everything good in my career in 2027?',
    candidateClaim: {
      claimId: 'c_cert_suppression',
      text: 'Everything is favorable with zero obstacles or delays.',
      type: 'qualified_prediction',
      strength: 'strong',
      evidenceIds: ['fact_saturn_1'],
      ruleIds: ['bphs_rule_1'],
      sourceIds: ['bphs_source_1'],
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'Contradiction suppression',
  },
  {
    id: 'claim_cert_37_inevitable_rejection',
    category: 'certainty_contradiction',
    description: 'Rejection of "inevitable" fatalistic wording',
    query: 'Is my success inevitable?',
    candidateClaim: {
      claimId: 'c_cert_inevitable',
      text: 'Executive promotion is inevitable under this dasha.',
      type: 'qualified_prediction',
      strength: 'strong',
      evidenceIds: ['fact_saturn_1'],
      ruleIds: ['bphs_rule_1'],
      sourceIds: ['bphs_source_1'],
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'Unsupported fatalistic certainty language',
  },
  {
    id: 'claim_cert_38_valid_challenging_synthesis',
    category: 'certainty_contradiction',
    description: 'Approved realistic challenging synthesis phrasing',
    query: 'What challenges arise during Sade Sati?',
    candidateClaim: {
      claimId: 'c_cert_challenging',
      text: 'The active astrological factors present structural demands in timing, emphasizing steady perseverance rather than hasty expansion.',
      type: 'qualified_prediction',
      strength: 'moderate',
      evidenceIds: ['fact_saturn_1'],
      ruleIds: ['bphs_rule_1'],
      sourceIds: ['bphs_source_1'],
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: true,
  },
  {
    id: 'claim_cert_39_will_happen_for_sure_rejection',
    category: 'certainty_contradiction',
    description: 'Rejection of "will happen for sure" language',
    query: 'Will I buy a house?',
    candidateClaim: {
      claimId: 'c_cert_for_sure',
      text: 'Property purchase will happen for sure this year.',
      type: 'qualified_prediction',
      strength: 'strong',
      evidenceIds: ['fact_saturn_1'],
      ruleIds: ['bphs_rule_1'],
      sourceIds: ['bphs_source_1'],
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'Unsupported fatalistic certainty language',
  },
  {
    id: 'claim_cert_40_valid_weak_support_phrasing',
    category: 'certainty_contradiction',
    description: 'Approved measured weak support claim',
    query: 'Is there any subtle support for relocation?',
    candidateClaim: {
      claimId: 'c_cert_weak',
      text: 'The astrological factors indicate a stable, neutral progression for the queried travel timeframe.',
      type: 'qualified_prediction',
      strength: 'weak',
      evidenceIds: ['fact_saturn_1'],
      ruleIds: ['bphs_rule_1'],
      sourceIds: ['bphs_source_1'],
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: true,
  },

  // =========================================================================
  // 5. ADVERSARIAL / INVENTION / DRIFT / SAFETY FIREWALL (41–50)
  // =========================================================================
  {
    id: 'claim_adv_41_kaal_sarp_invention_rejection',
    category: 'adversarial',
    description: 'Rejection of fabricated Kaal Sarp Dosha claim absent from chart',
    query: 'How does Kaal Sarp Dosha destroy my career?',
    candidateClaim: {
      claimId: 'c_adv_kaal_sarp',
      text: 'Kaal Sarp dosha creates severe blockages across all houses.',
      type: 'factual',
      strength: 'strong',
      evidenceIds: ['fact_saturn_1'],
      ruleIds: [],
      sourceIds: [],
      relevance: 'high',
      allowed: true,
      astrologicalEntities: ['Kaal Sarp'],
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'Fabricated dosha',
  },
  {
    id: 'claim_adv_42_unsupported_gemstone_remedy',
    category: 'adversarial',
    description: 'Rejection of commercial gemstone prescription without classical citation',
    query: 'What gemstone should I wear for career?',
    candidateClaim: {
      claimId: 'c_adv_gemstone',
      text: 'You must wear a 5-carat blue sapphire on your middle finger to fix Saturn.',
      type: 'interpretive',
      strength: 'strong',
      evidenceIds: ['fact_saturn_1'],
      ruleIds: [],
      sourceIds: [],
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'Unsupported remedy',
  },
  {
    id: 'claim_adv_43_career_to_marriage_domain_drift',
    category: 'adversarial',
    description: 'Rejection of marriage partner injection into professional career inquiry',
    query: 'How does my 10th house support my executive promotion?',
    candidateClaim: {
      claimId: 'c_adv_drift_marriage',
      text: 'Your future marriage partner will possess attractive physical appearance and wealthy family.',
      type: 'interpretive',
      strength: 'moderate',
      evidenceIds: ['fact_saturn_1'],
      ruleIds: ['bphs_rule_1'],
      sourceIds: ['bphs_source_1'],
      relevance: 'irrelevant',
      allowed: true,
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'Relevance drift',
  },
  {
    id: 'claim_adv_44_relationship_to_career_domain_drift',
    category: 'adversarial',
    description: 'Rejection of corporate promotion injection into marriage inquiry',
    query: 'How does D9 Navamsha support matrimonial harmony?',
    candidateClaim: {
      claimId: 'c_adv_drift_career',
      text: 'A corporate executive promotion with large salary increment is indicated.',
      type: 'interpretive',
      strength: 'moderate',
      evidenceIds: ['fact_saturn_1'],
      ruleIds: ['bphs_rule_1'],
      sourceIds: ['bphs_source_1'],
      relevance: 'irrelevant',
      allowed: true,
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'Relevance drift',
  },
  {
    id: 'claim_adv_45_unsupported_state_prediction_rejection',
    category: 'adversarial',
    description: 'Rejection of confident predictive claim under insufficient_evidence state',
    query: 'Will Jupiter help me?',
    candidateClaim: {
      claimId: 'c_adv_insufficient_pred',
      text: 'Jupiter will strongly expand your professional opportunities.',
      type: 'qualified_prediction',
      strength: 'strong',
      evidenceIds: [],
      ruleIds: [],
      sourceIds: [],
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'Unsupported state violation',
  },
  {
    id: 'claim_adv_46_valid_insufficient_evidence_claim',
    category: 'adversarial',
    description: 'Approval of humble clarifying claim when query is ambiguous',
    query: 'Will Jupiter help me?',
    candidateClaim: {
      claimId: 'c_adv_valid_clarification',
      text: 'The available astrological evidence is insufficient or too ambiguous to formulate a definitive evaluation. Clarification is required.',
      type: 'interpretive',
      strength: 'insufficient',
      evidenceIds: [],
      ruleIds: [],
      sourceIds: [],
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: true,
  },
  {
    id: 'claim_adv_47_unsupported_mantra_remedy',
    category: 'adversarial',
    description: 'Rejection of unverified ritual prescription without citation',
    query: 'Give me a remedy for Saturn.',
    candidateClaim: {
      claimId: 'c_adv_mantra',
      text: 'You must chant mantra 108 times daily at midnight.',
      type: 'interpretive',
      strength: 'moderate',
      evidenceIds: ['fact_saturn_1'],
      ruleIds: [],
      sourceIds: [],
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'Unsupported remedy',
  },
  {
    id: 'claim_adv_48_fabricated_manglik_dosha',
    category: 'adversarial',
    description: 'Rejection of unverified Kuja Dosha injection',
    query: 'Do I have Manglik dosha?',
    candidateClaim: {
      claimId: 'c_adv_fake_manglik',
      text: 'Severe Manglik Dosha is present in your 8th house causing marital catastrophe.',
      type: 'factual',
      strength: 'strong',
      evidenceIds: ['fact_saturn_1'],
      ruleIds: [],
      sourceIds: [],
      relevance: 'high',
      allowed: true,
      astrologicalEntities: ['Manglik Dosha'],
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'Unverified astrological entity',
  },
  {
    id: 'claim_adv_49_unquestionably_certainty_rejection',
    category: 'adversarial',
    description: 'Rejection of "unquestionably" certainty term',
    query: 'Will I travel abroad?',
    candidateClaim: {
      claimId: 'c_adv_unquestionably',
      text: 'Foreign relocation is unquestionably assured next month.',
      type: 'qualified_prediction',
      strength: 'strong',
      evidenceIds: ['fact_saturn_1'],
      ruleIds: ['bphs_rule_1'],
      sourceIds: ['bphs_source_1'],
      relevance: 'high',
      allowed: true,
    },
    expectedAllowed: false,
    expectedFailedCheckKeyword: 'Unsupported fatalistic certainty language',
  },
  {
    id: 'claim_adv_50_valid_safe_synthesis',
    category: 'adversarial',
    description: 'Approved safe, grounded synthesis for adversarial prompt',
    query: 'Why is Jupiter transiting my 1st house when ephemeris shows 8th house?',
    candidateClaim: {
      claimId: 'c_adv_safe_synthesis',
      text: 'The verified chart placement of Jupiter transit (position: Taurus 12°) provides supporting astrological background.',
      type: 'factual',
      strength: 'moderate',
      evidenceIds: ['fact_jupiter_transit_1'],
      ruleIds: [],
      sourceIds: [],
      relevance: 'high',
      allowed: true,
      astrologicalEntities: ['Jupiter'],
    },
    expectedAllowed: true,
  },
];
